export const RECORD_ADDRESS = 'RECORD_ADDRESS'
export const SAVE_GEOHASH = 'SAVE_GEOHASH'
export const RECORD_USERINFO = 'RECORD_USERINFO'
export const GET_USERINFO = 'GET_USERINFO'
//加车
export const ADD_CART = 'ADD_CART'
//购物车信息
export const REDUCE_CART = 'REDUCE_CART'
//初始化购物车
export const INIT_BUYCART = 'INIT_BUYCART'
//清空购物车
export const CLEAR_CART = 'CLEAR_CART'
//记录商家信息
export const RECORD_SHOPDETAIL = 'RECORD_SHOPDETAIL'
export const CHOOSE_ADDRESS = 'CHOOSE_ADDRESS'
export const NEED_VALIDATION = 'NEED_VALIDATION'
export const SAVE_CART_ID_SIG = 'SAVE_CART_ID_SIG'
export const SAVE_ORDER_PARAM = 'SAVE_ORDER_PARAM'
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const SAVE_SHOPID = 'SAVE_SHOPID'
export const CHOOSE_SEARCH_ADDRESS = 'CHOOSE_SEARCH_ADDRESS'

export const CHANGE_ORDER_PARAM = 'CHANGE_ORDER_PARAM'

export const CONFIRM_REMARK = 'CONFIRM_REMARK'
export const CONFIRM_ADDRESS = 'CONFIRM_ADDRESS'

export const SAVE_ORDER = 'SAVE_ORDER'

export const OUT_LOGIN = 'OUT_LOGIN'

export const SAVE_AVANDER = 'SAVE_AVANDER'

export const RETSET_NAME = 'RETSET_NAME'

export const SAVE_ADDRESS = 'SAVE_ADDRESS'

export const SAVE_ADDDETAIL = 'SAVE_ADDDETAIL'
export const ADD_ADDRESS = 'ADD_ADDRESS'
